package damas.entity;
// Generated 31-ene-2021 22:17:47 by Hibernate Tools 4.3.1



/**
 * DatosPartida generated by hbm2java
 */
public class DatosPartida  implements java.io.Serializable {


     private Integer id;
     private boolean turno;
     private boolean jugando;

    public DatosPartida() {
    }

    public DatosPartida(boolean turno, boolean jugando) {
       this.turno = turno;
       this.jugando = jugando;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public boolean isTurno() {
        return this.turno;
    }
    
    public void setTurno(boolean turno) {
        this.turno = turno;
    }
    public boolean isJugando() {
        return this.jugando;
    }
    
    public void setJugando(boolean jugando) {
        this.jugando = jugando;
    }




}


